apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "aks-rbac.fullname" .}}
rules:
- apiGroups: [""] # empty "" api group indicates the core API group
  resources: ["namespaces"]
  verbs: ["list"]
