apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ template "aks-rbac.fullname" . }}
subjects:
{{- range .Values.securityGroupIDs }}
- kind: Group
  name: {{ . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}    
roleRef:
  kind: Role 
  name: {{ template "aks-rbac.fullname" . }}
  apiGroup: rbac.authorization.k8s.io